### ISSUE TITLE
 java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by nelson2005** [saurfang/spark-sas7bdat#35]
I get this error loading a not-small dataset.  I filed the [main issue report](https://github.com/epam/parso/issues/29) over on @epam's [parso](https://github.com/epam/parso) site, but am wondering if there's something about this project's usage of parso that could be related or worked around.  (as in, would turning off compression make this dataset splittable and work around this problem?)

Stack trace is 
Caused by: java.lang.ArrayIndexOutOfBoundsException
        at java.util.Arrays.copyOfRange(Arrays.java:3521)
        at com.epam.parso.impl.SasFileParser.getBytesFromFile(SasFileParser.java:717)
        at com.epam.parso.impl.SasFileParser.readSubheaderSignature(SasFileParser.java:403)
        at com.epam.parso.impl.SasFileParser.processPageMetadata(SasFileParser.java:372)
        at com.epam.parso.impl.SasFileParser.processNextPage(SasFileParser.java:566)
        at com.epam.parso.impl.SasFileParser.readNextPage(SasFileParser.java:544)
... 45 more

**Comment by nelson2005** [comment]
This is a knock-on-effect of the non-splittability caused by SAS dataset internal compression, which is usually turned on by default.

One possible solution would be to make the reader aware of some other splittable compression like lzo.  At any rate, this problem can be worked around using a statement like

options compress=off;

prior to saving a sas7bdat.
