### ISSUE TITLE
SAS7BDAT read issue (java.util.Arrays$ArrayList cannot be cast to java.util.Set)

### ISSUE THREAD

**Issue by chonterry** [saurfang/spark-sas7bdat#54]
I get the following error when I execute the following:

df = sqlContext.read.format("com.github.saurfang.sas.spark").load('sas7bdat path')

Any idea what may be causing this issue?

error:

py4j.protocol.Py4JJavaError: An error occurred while calling o66.load.
: java.lang.ClassCastException: java.util.Arrays$ArrayList cannot be cast to java.util.Set
	at com.github.saurfang.sas.parso.ParsoWrapper$.DATE_FORMAT_STRINGS$lzycompute(ParsoWrapper.scala:39)
	at com.github.saurfang.sas.parso.ParsoWrapper$.DATE_FORMAT_STRINGS(ParsoWrapper.scala:36)
	at com.github.saurfang.sas.spark.SasRelation.inferSchema(SasRelation.scala:201)
	at com.github.saurfang.sas.spark.SasRelation.<init>(SasRelation.scala:62)
	at com.github.saurfang.sas.spark.SasRelation$.apply(SasRelation.scala:43)
	at com.github.saurfang.sas.spark.DefaultSource.createRelation(DefaultSource.scala:209)
	at com.github.saurfang.sas.spark.DefaultSource.createRelation(DefaultSource.scala:42)
	at com.github.saurfang.sas.spark.DefaultSource.createRelation(DefaultSource.scala:27)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:318)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:223)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:178)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

**Comment by chonterry** [comment]
Sorry.  Issue resolved.  Please ensure that you are using 2.0.10.  I was originally using 2.0..
