### ISSUE TITLE
    UNRESOLVED DEPENDENCIES  

### ISSUE THREAD

**Issue by Kalyan-D** [saurfang/spark-sas7bdat#65]
:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: saurfang#spark-sas7bdat;3.0.0-s_2.12: not found]
        at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1304)
        at org.apache.spark.deploy.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:54)
        at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:304)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:776)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:922)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:931)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by thesuperzapper** [comment]
@Kalyan-D the bintray repository has been sunset according to: https://spark.apache.org/news/new-repository-service.html

You will need to update to a newer version of spark `2.4.8`, `3.0.3` or `3.1.2` (which are not all out yet) to continue using the `--packages` method, otherwise you will need to pass the [spark-sas7bdat jar](https://spark-packages.org/package/saurfang/spark-sas7bdat) and [parso jar](https://mvnrepository.com/artifact/com.epam/parso/2.0.11) with `--jars`.
